"""initial with constraints

Revision ID: a109d0ae1db1
Revises: 
Create Date: 2026-09-10 11:38:06.944875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a109d0ae1db1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.alter_column('tmdb_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('genre',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'movies', ['tmdb_id'], ['tmdb_id'], ondelete='CASCADE')

    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.alter_column('tmdb_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('average_rating',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.create_index('idx_movies_date', ['date'], unique=False)
        batch_op.create_index('idx_movies_title', ['title'], unique=False)

    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.alter_column('tmdb_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('rating',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('tmdb_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_index('idx_movies_title')
        batch_op.drop_index('idx_movies_date')
        batch_op.alter_column('average_rating',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.Text(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('tmdb_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'movies', ['tmdb_id'], ['tmdb_id'])
        batch_op.alter_column('genre',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('tmdb_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
